import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

import { useSession, signOut, signIn } from "next-auth/react"
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { data, status } = useSession()
  return (
    <>
      <Head>
        <title>next-auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-center border'>
        <div className='border  m-10 p-10'>
          <h1 className='text-4xl'>NextAuth</h1>
          <h3>status:{status}</h3>
          <Link className='text-red-500 hover:text-blue-500' href='/api/auth/signin'>
            go to sign in page
          </Link>

          <pre>{JSON.stringify(data, null, 2)}</pre>
          {data && <button className='border text-red-500 hover:text-blue-500 rounded-lg p-2' onClick={signOut}>sign out</button>}
          {!data && <button className='border text-red-500 hover:text-blue-500 rounded-lg p-2' onClick={() => signIn('google')}>sign in with google</button>}
        </div>

        {!data && <SignInFrom />}

      </main>
    </>
  )
}


function SignInFrom() {

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  function handleSignIn(e) {
    e.preventDefault()
    // signIn('credentials', { email, password })
    signIn('credentials', { email, password, callbackUrl: '/test' })
  }

  return (

    <div className='container mx-auto flex justify-center'>
      <form onSubmit={handleSignIn} className='my-10 border border-black w-96 p-10'>
        <input className='border border-black p-2' type='text' value={email} placeholder='email' onChange={e => setEmail(e.target.value)} />
        <br />
        <br />
        <input className='border border-black p-2' type='text' value={password} placeholder='password' onChange={e => setPassword(e.target.value)} />
        <br />
        <br />
        <button className='border border-black rounded-xl p-2' type='submit'>Login</button>

      </form>
    </div>
  )
}